# Generated by Django 5.2.16 on 2026-08-03 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='parent_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='files.attachment'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
