# Generated by Django 5.2.16 on 2026-08-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_board_column'),
        ('tasks', '0002_tag_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_time',
            field=models.FloatField(blank=True, help_text='Actual hours logged', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.column'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.FloatField(blank=True, help_text='Estimated hours', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
