# Generated by Django 5.2.16 on 2026-08-02 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#4F46E5', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, default='briefcase', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='permission',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('team', 'Team Only')], default='team', max_length=20),
        ),
    ]
