# Generated by Django 5.2.16 on 2026-08-06 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.role'),
        ),
    ]
